name: Trigger auto deployment for spring-openai-bot

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/spring-openai-bot-AutoDeployTrigger-0575ce77-139b-42f4-8ebb-3fcfb52d9eeb.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'microsoft'
          cache: maven
      - name: Build with Maven Wrapper
        run: ./mvnw -B package
        
      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca06b1fe1cecacr.azurecr.io
          username: ${{ secrets.SPRINGOPENAIBOT_REGISTRY_USERNAME }}
          password: ${{ secrets.SPRINGOPENAIBOT_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca06b1fe1cecacr.azurecr.io/spring-openai-bot:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SPRINGOPENAIBOT_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n spring-openai-bot -g petclinic --server ca06b1fe1cecacr.azurecr.io --username  ${{ secrets.SPRINGOPENAIBOT_REGISTRY_USERNAME }} --password ${{ secrets.SPRINGOPENAIBOT_REGISTRY_PASSWORD }}
            az containerapp update -n spring-openai-bot -g petclinic --image ca06b1fe1cecacr.azurecr.io/spring-openai-bot:${{ github.sha }}
